// Code generated by "stringer -output=string.go -type=DUIDType"; DO NOT EDIT.

package dhcp6opts

import "fmt"

const _DUIDType_name = "DUIDTypeLLTDUIDTypeENDUIDTypeLLDUIDTypeUUID"

var _DUIDType_index = [...]uint8{0, 11, 21, 31, 43}

func (i DUIDType) String() string {
	i -= 1
	if i >= DUIDType(len(_DUIDType_index)-1) {
		return fmt.Sprintf("DUIDType(%d)", i+1)
	}
	return _DUIDType_name[_DUIDType_index[i]:_DUIDType_index[i+1]]
}
